DROP TABLE IF EXISTS cats;

CREATE TABLE cats(
    catId INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (100) NOT NULL,
    mom VARCHAR(100),
    dad VARCHAR(100),
    color VARCHAR(100) NOT NULL,
    race ENUM('BRITISH_SHORTHAIR', 'MAINE_COON', 'NORSK_SKOVKAT') NOT NULL

)engine=InnoDB;